- name: Check if kubectl is installed
  command: kubectl version --client
  register: kubectl_version
  ignore_errors: true
  changed_when: false

- name: Download kubectl if not installed
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: kubectl_download
  when: kubectl_version.rc != 0

- name: Download the latest kubectl release
  uri:
    url: https://dl.k8s.io/release/{{ version.content }}/bin/linux/arm/kubectl
    dest: /home/{{ ansible_user }}
  register: kubectl_download
  ignore_errors: true
  when: kubectl_download.changed

- name: Remove existing kubectl binary
  file:
    path: /usr/local/bin/kubectl
    state: absent
  when: kubectl_download.changed

- name: Move kubectl and change permissions
  copy:
    src: "/home/{{ ansible_user }}/kubectl"
    dest: /usr/local/bin/kubectl
    remote_src: yes
    owner: root
    group: root
    mode: '+x'
  when: kubectl_download.changed

