---
- name: Get latest kubectl version
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: version

- name: Download the latest kubectl release
  uri:
    url: https://dl.k8s.io/release/{{ version.content }}/bin/linux/arm/kubectl
    dest: /home/{{ ansible_user }}
  register: kubectl

- name: Remove existing kubectl binary
  file:
    path: /usr/local/bin/kubectl
    state: absent

- name: Move kubectl and change permissions
  copy:
    src: "{{ kubectl.path }}"
    dest: /usr/local/bin/kubectl
    remote_src: yes
    owner: root
    group: root
    mode: '+x'

#TODO check if a newer version of kubectl avaiable then download, else skip this
