---
- name: Get latest kubectl version
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: version

- name: Download the latest kubectl release
  uri:
    url: https://dl.k8s.io/release/{{ version.content }}/bin/linux/arm/kubectl
    dest: /home/{{ ansible_user }}
  register: kubectl
  ignore_errors: yes

- name: Remove existing kubectl binary
  file:
    path: /usr/local/bin/kubectl
    state: absent
  when: kubectl.changed or kubectl.failed

- name: Move kubectl and change permissions
  copy:
    src: "/home/{{ ansible_user }}/kubectl"
    dest: /usr/local/bin/kubectl
    remote_src: yes
    owner: root
    group: root
    mode: '+x'
  when: kubectl.changed or kubectl.failed

