- name: Install and configure the Prometheus server
  vars:
    prometheus_url: "prometheus.insightsphere.com"
    prometheus_chart_name: "prometheus"
  tasks:
    - name: Add the prometheus helm repository
      ansible.builtin.shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Update repositories list
      ansible.builtin.shell: helm repo update

    - name: Check the list of installed Helm Charts
      ansible.builtin.shell: helm ls -q
      register: helm_charts

    - name: Installing the prometheus helm chart if not exists
      ansible.builtin.shell: "helm install {{ prometheus_chart_name }} prometheus-community/kube-prometheus-stack \
                              --set kubeStateMetrics.enabled=false,nodeExporter.enabled=false,pushgateway.enabled=false"
      when: prometheus_chart_name not in helm_charts.stdout

    - name: Check the Nginx Ingress IP address
      ansible.builtin.shell: kubectl get svc nginx-ingress-controller -o=jsonpath='{.status.loadBalancer.ingress[0].ip}'
      register: nginx_ingress_ip

    - name: Add the Prometheus server URL to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ nginx_ingress_ip.stdout }}    {{ prometheus_url }}"
      when: not grep -q "{{ nginx_ingress_ip.stdout }}    {{ prometheus_url }}" /etc/hosts

