- name: Run the script to install and run the exporters
  script: automated_prometheus_agent_installation.sh "{{ item }}"
  loop: "{{ exporters_types }}"
  become: yes
  when: "'node_exporters' in group_names and item == 'node_exporter' or 'network' in group_names and item == 'snmp_exporter'"
  register: script_result


- name: Check if exporter is downloaded from GitHub
  debug:
     msg: "{{ item.item }} downloaded successfully from GitHub"
  loop: "{{ script_result.results }}"
  when: "item.stdout is defined and ('Successfully downloaded' in item.stdout)"
  loop_control:
    label: "{{ item.item }}"

- name: Check if exporter is not downloaded from GitHub
  fail:
    msg: "Failed to download the {{ item.item }} from GitHub. Check internet connection and try again."
  loop: "{{ script_result.results }}"
  when: "item.rc is defined and item.rc == 1"
  loop_control:
    label: "{{ item.item }}"


- name: Check if exporter service is up and running
  debug:
    msg: "{{ item.item }} is up and running"
  loop: "{{ script_result.results }}"
  when: "item.stdout is defined and ('successfully created' in item.stdout)"
  loop_control:
    label: "{{ item.item }}"


- name: Check if exproter service is not up and running
  fail:
    msg: "{{ item.item }} encountered an issue. Please check configuration and try again."
  loop: "{{ script_result.results }}"
  when: "item.rc is defined and item.rc == 2"
  loop_control:
    label: "{{ item.item }}"




