---
- include_vars: ../../../values.yml

- name: Run the script to install and run the exporters
  script: automated_prometheus_agent_installation.sh "{{ item }}"
  loop: "{{ exporters_types }}"
  register: script_output
  ignore_errors: true

- name: Check if script downloaded the exporter successfully
  debug:
    msg: "Exporter was downloaded successfully."
  when: item.rc == 0
  loop: "{{ script_output.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Handle error when invalid exporter type is provided
  debug:
    msg: "Error: Invalid exporter type or unsupported type in download function."
  when: item.rc == 1
  loop: "{{ script_output.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Handle error when failed to download the exporter package
  debug:
    msg: "Error: Failed to download the exporter package."
  when: item.rc == 2
  loop: "{{ script_output.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Handle error when exporter failed to start
  debug:
    msg: "Error: Exporter failed to start or is not running as expected."
  when: item.rc == 3
  loop: "{{ script_output.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Handle error when kubectl or helm is not installed
  debug:
    msg: "Error: Could not download kubernetes exporter because kubectl or helm is not installed on target machine"
  when: item.rc == 4
  loop: "{{ script_output.results }}"
  loop_control:
    label: "{{ item.item }}"


