apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myapp-tls
  namespace: default
spec:
  issuerRef:
    name: selfsigned-clusterissuer
    kind: ClusterIssuer
  secretName: insightsphere-tls-secret
  dnsNames:
    - grafana.insightsphere.com
    - prometheus.insightsphere.com
