apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-production-cert
  namespace: default # remove me when moving project to diffrent namespace
spec:
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: letsencrypt-production-secret
  dnsNames:
     grafana.insightsphere.com
     prometheus.insightsphere.com
