alertmanager:
  config:
    global:
      pagerduty_url: https://events.pagerduty.com/generic/2010-04-15/create_event.json
      resolve_timeout: 5m
    receivers:
    - name: pagerduty
      pagerduty_configs:
      - service_key: e492c97a99214c07c0681a5c2da95943
    route:
      group_by:
      - cluster
      group_interval: 10m
      group_wait: 10s
      receiver: pagerduty
      repeat_interval: 1h
      routes:
      - receiver: pagerduty
  enable: true
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
prometheus-pushgateway:
  enabled: false
serverFiles:
  alerting_rules.yml:
    groups:
    - name: node_exporter alerts
      rules:
      - alert: HostHighCpuLoad
        annotations:
          description: |-
            CPU load is > 80%
              VALUE = {{ $value }}
              LABELS = {{ $labels }}
          summary: Host high CPU load (instance {{ $labels.instance }})
        expr: (sum by (instance) (avg by (mode, instance) (rate(node_cpu_seconds_total{mode!="idle"}[2m])))
          > 0.8) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 10m
        labels:
          severity: warning
      - alert: HostOutOfMemory
        annotations:
          description: |-
            Node memory is filling up (< 10% left)
              VALUE = {{ $value }}
              LABELS = {{ $labels }}
          summary: Host out of memory (instance {{ $labels.instance }})
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 <
          10) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
        for: 2m
        labels:
          severity: warning
    - name: snmp_exporter alerts
      rules:
      - alert: SNMPAgentDown
        annotations:
          description: The SNMP agent on {{ $labels.instance }} has been down for
            more than 5 minutes.
          summary: SNMP agent is down on {{ $labels.instance }}
        expr: up == 0
        for: 5m
        labels:
          severity: critical
      - alert: InterfaceDown
        annotations:
          description: The interface {{ $labels.ifDescr }} has been down for more
            than 5 minutes on {{ $labels.instance }}.
          summary: Interface {{ $labels.ifDescr }} is down on {{ $labels.instance
            }}
        expr: snmp_ifOperStatus != 1
        for: 5m
        labels:
          severity: critical
      - alert: HighInterfaceUtilization
        annotations:
          description: The interface {{ $labels.ifDescr }} on {{ $labels.instance
            }} has been utilizing more than 80% of its bandwidth for more than 10
            minutes.
          summary: High interface utilization on {{ $labels.ifDescr }} ({{ $labels.instance
            }})
        expr: (rate(snmp_ifOutOctets[5m]) * 8 + rate(snmp_ifInOctets[5m]) * 8) / snmp_ifSpeed
          * 100 > 80
        for: 10m
        labels:
          severity: warning

