- name: Check if Docker is installed
  shell: docker --version >/dev/null 2>&1
  register: docker_installed
  changed_when: false
  ignore_errors: true

- name: Install Docker dependencies
  ansible.builtin.dnf:
    name:
      - curl
      - ca-certificates
      - gnupg2
  when: docker_installed.rc != 0

- name: Add Docker's official GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://download.docker.com/linux/centos/gpg
  when: docker_installed.rc != 0

- name: Add Docker repository
  ansible.builtin.yum_repository:
    name: Docker
    description: Docker Repository
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes
  when: docker_installed.rc != 0

- name: Install Docker and related packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
  when: docker_installed.rc != 0

- name: Add Docker group
  ansible.builtin.group:
    name: docker
    state: present
  when: docker_installed.rc != 0

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  when: docker_installed.rc != 0

- name: Enable and start Docker services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service
    - containerd.service
  when: docker_installed.rc != 0

