- name: Check if Kind is installed
  shell: find / -type f -name kind -executable 2>/dev/null || true
  register: kind_check
  changed_when: false

- name: Download Kind if not installed
  ansible.builtin.shell: |
    curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
    chmod +x ./kind
    mv ./kind /usr/local/bin/kind
  args:
    creates: /usr/local/bin/kind
  when: kind_check.rc != 0

