---
- include_vars: ../../../values.yml

- name: Add the Grafana helm repository
  ansible.builtin.shell: helm repo add grafana https://grafana.github.io/helm-charts

- name: Update repositories list
  ansible.builtin.shell: helm repo update

- name: Check the list of installed Helm Charts
  ansible.builtin.shell: helm ls -q
  register: helm_charts

- name: Installing the Grafana helm chart if not exists
  ansible.builtin.shell: "helm install {{ grafana_chart_name }} grafana/grafana"
  when: grafana_chart_name not in helm_charts.stdout

- name: Check the Nginx Ingress IP address
  ansible.builtin.shell: kubectl get svc nginx-ingress-controller -o=jsonpath='{.status.loadBalancer.ingress[0].ip}'
  register: nginx_ingress_ip

- name: Check if the Grafana server URL is in /etc/hosts
  ansible.builtin.command: "grep -q '{{ nginx_ingress_ip.stdout }}    {{ grafana_url }}' /etc/hosts"
  register: grep_result
  ignore_errors: true

- name: Add the Grafana server URL to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ nginx_ingress_ip.stdout }}    {{ grafana_url }}"
  when: grep_result.rc != 0


