- name: Check if Helm is installed
  shell: find / -type f -name helm -executable 2>/dev/null || true
  register: helm_check
  changed_when: false

- name: Install Helm if not exists
  unarchive:
    src: https://get.helm.sh/helm-v3.13.1-linux-amd64.tar.gz
    dest: /usr/local/bin
    extra_opts: "--strip-components=1"
    owner: root
    group: root
    mode: 0755
    remote_src: true
  when: helm_check.rc != 0

