---
  
- name: Apply alert rules
  script: apply_alert_rules.sh
  register: script_output

- name: Show the script output
  ansible.builtin.debug:
    var: script_output.stdout


- name: Apply AlertManager configuration
  shell: helm upgrade prometheus prometheus-community/prometheus -f {{ role_path }}/files/alertmanager_config.yaml --reuse-values

