- name: Run the grafana password script
  ansible.builtin.script: grafana_password.sh

- name: Give insecure permissions to an existing file
  ansible.builtin.file:
    path: grafana_password.yml
    owner: root
    group: root
    mode: '0400'

