---
- name: Copy the Kind cluster configuration file to the managed node
  ansible.builtin.copy:
    src: prom-graf-cluster.yaml
    dest: /tmp/prom-graf-cluster.yaml

- name: Create the Kind Cluster
  ansible.builtin.shell:
    cmd: "kind create cluster --config /tmp/prom-graf-cluster.yaml"

