---
- name: Deploy Kubernetes cluster with Prometheus and Grafana
  hosts: local
  roles:
    - role: system-upgrade
      tags: [system-upgrade, prerequisites]
    - role: docker
      tags: [docker, prerequisites]
    - role: kubectl
      tags: [kubectl, prerequisites]
    - role: kind
      tags: [kind, prerequisites]
    - role: helm
      tags: [helm, prerequisites]
    - role: python
      tags: [python, prerequisites]
    - role: cluster
      tags: [cluster, cluster-setup]
    - role: cert-manager
      tags: [cert-manager, cluster-setup]
    - role: metallb
      tags: [metallb, cluster-setup]
    - role: nginx-ingress
      tags: [nginx-ingress, cluster-setup]
    - role: prometheus
      tags: [prometheus, monitoring-setup]
    - role: grafana
      tags: [grafana, monitoring-setup]
    - role: ingress
      tags: [ingress, configuration]
    - role: prometheus_scrape_config
      tags: [prometheus_scrape_config, configuration]
    - role: grafana_dashboard_config
      tags: [grafana_dashboard_config, configuration]
    - role: alert_manager
      tags: [alert_manager, configuration]
    - role: fetch_grafana_password
      tags: [fetch_grafana_password, configuration]

- name: Run exporters_installation on specific hosts
  hosts: node_exporters:network
  roles:
    - role: exporters_installation
      tags: exporters_installation

